<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentSampleSeeder extends Seeder
{
    public function run(): void
    {
        $samples = [
            [
                'id_number' => '24-10001',
                'lastname' => 'Dela Cruz',
                'firstname' => 'Juan',
                'middle_initial' => 'M',
                'birthday' => '2004-03-15',
                'qrcode' => 'S-00000001',
                'course' => 'BSCS',
                'year' => '1st Year',
                'mobile_number' => '09171234501',
                'address' => '123 Rizal St, Koronadal City',
                'emergency_person' => 'Maria Dela Cruz',
                'emergency_relationship' => 'Mother',
                'emergency_number' => '09181234501',
                'emergency_address' => '123 Rizal St, Koronadal City',
            ],
            [
                'id_number' => '24-10002',
                'lastname' => 'Santos',
                'firstname' => 'Ana',
                'middle_initial' => 'L',
                'birthday' => '2003-07-22',
                'qrcode' => 'S-00000002',
                'course' => 'BEED',
                'year' => '2nd Year',
                'mobile_number' => '09171234502',
                'address' => '45 Mabini Ave, General Santos City',
                'emergency_person' => 'Pedro Santos',
                'emergency_relationship' => 'Father',
                'emergency_number' => '09181234502',
                'emergency_address' => '45 Mabini Ave, General Santos City',
            ],
            [
                'id_number' => '24-10003',
                'lastname' => 'Reyes',
                'firstname' => 'Mark',
                'middle_initial' => 'D',
                'birthday' => '2002-11-08',
                'qrcode' => 'S-00000003',
                'course' => 'BSIT',
                'year' => '3rd Year',
                'mobile_number' => '09171234503',
                'address' => '78 Quezon Blvd, Tacurong City',
                'emergency_person' => 'Liza Reyes',
                'emergency_relationship' => 'Mother',
                'emergency_number' => '09181234503',
                'emergency_address' => '78 Quezon Blvd, Tacurong City',
            ],
            [
                'id_number' => '24-10004',
                'lastname' => 'Garcia',
                'firstname' => 'Sophia',
                'middle_initial' => 'R',
                'birthday' => '2005-01-30',
                'qrcode' => 'S-00000004',
                'course' => 'BSED',
                'year' => '1st Year',
                'mobile_number' => '09171234504',
                'address' => '12 Luna St, Kidapawan City',
                'emergency_person' => 'Rosa Garcia',
                'emergency_relationship' => 'Guardian',
                'emergency_number' => '09181234504',
                'emergency_address' => '12 Luna St, Kidapawan City',
            ],
            [
                'id_number' => '24-10005',
                'lastname' => 'Mendoza',
                'firstname' => 'Carlos',
                'middle_initial' => 'P',
                'birthday' => '2001-09-12',
                'qrcode' => 'S-00000005',
                'course' => 'BSCS',
                'year' => '4th Year',
                'mobile_number' => '09171234505',
                'address' => '90 Bonifacio St, Cotabato City',
                'emergency_person' => 'Elena Mendoza',
                'emergency_relationship' => 'Mother',
                'emergency_number' => '09181234505',
                'emergency_address' => '90 Bonifacio St, Cotabato City',
            ],
            [
                'id_number' => '24-10006',
                'lastname' => 'Torres',
                'firstname' => 'Grace',
                'middle_initial' => 'A',
                'birthday' => '2003-05-18',
                'qrcode' => 'S-00000006',
                'course' => 'BSBA',
                'year' => '2nd Year',
                'mobile_number' => '09171234506',
                'address' => '34 Aguinaldo St, Digos City',
                'emergency_person' => 'Jose Torres',
                'emergency_relationship' => 'Father',
                'emergency_number' => '09181234506',
                'emergency_address' => '34 Aguinaldo St, Digos City',
            ],
            [
                'id_number' => '24-10007',
                'lastname' => 'Flores',
                'firstname' => 'Daniel',
                'middle_initial' => 'B',
                'birthday' => '2004-12-05',
                'qrcode' => 'S-00000007',
                'course' => 'BSIT',
                'year' => '1st Year',
                'mobile_number' => '09171234507',
                'address' => '56 Roxas Ave, Polomolok',
                'emergency_person' => 'Carmen Flores',
                'emergency_relationship' => 'Mother',
                'emergency_number' => '09181234507',
                'emergency_address' => '56 Roxas Ave, Polomolok',
            ],
            [
                'id_number' => '24-10008',
                'lastname' => 'Ramos',
                'firstname' => 'Isabella',
                'middle_initial' => 'C',
                'birthday' => '2002-08-27',
                'qrcode' => 'S-00000008',
                'course' => 'BEED',
                'year' => '3rd Year',
                'mobile_number' => '09171234508',
                'address' => '21 Burgos St, Surallah',
                'emergency_person' => 'Antonio Ramos',
                'emergency_relationship' => 'Father',
                'emergency_number' => '09181234508',
                'emergency_address' => '21 Burgos St, Surallah',
            ],
            [
                'id_number' => '24-10009',
                'lastname' => 'Bautista',
                'firstname' => 'Miguel',
                'middle_initial' => 'T',
                'birthday' => '2003-04-14',
                'qrcode' => 'S-00000009',
                'course' => 'BSCS',
                'year' => '2nd Year',
                'mobile_number' => '09171234509',
                'address' => '67 Del Pilar St, Tupi',
                'emergency_person' => 'Teresa Bautista',
                'emergency_relationship' => 'Mother',
                'emergency_number' => '09181234509',
                'emergency_address' => '67 Del Pilar St, Tupi',
            ],
            [
                'id_number' => '24-10010',
                'lastname' => 'Castillo',
                'firstname' => 'Elena',
                'middle_initial' => 'V',
                'birthday' => '2001-06-09',
                'qrcode' => 'S-00000010',
                'course' => 'BSN',
                'year' => '4th Year',
                'mobile_number' => '09171234510',
                'address' => '88 Jacinto St, Banga',
                'emergency_person' => 'Victor Castillo',
                'emergency_relationship' => 'Father',
                'emergency_number' => '09181234510',
                'emergency_address' => '88 Jacinto St, Banga',
            ],
        ];

        foreach ($samples as $data) {
            Student::updateOrCreate(
                ['qrcode' => $data['qrcode']],
                $data
            );
        }

        $this->command?->info('10 sample students seeded (QR codes S-00000001 … S-00000010).');
    }
}
